spring:
        datasource:
                driverClassName: com.mysql.jdbc.Driver
                url: jdbc:mysql://localhost:3306/test
                username: testuser
                password: testpassword
